#!/usr/bin/env bash
# Ayra - UserBot
# Copyright (C) 2021-2022 senpai80
#
# This file is a part of < https://github.com/senpai80/Ayra/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/senpai80/Ayra/blob/main/LICENSE/>.


echo "
            
                 ᴋᴀᴢᴜ ᴜʙᴏᴛ​


"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.githubusercontent.com/ionmusic/b93f641c0caef18d494205e5ae14adc7/raw/main.py && python3 main.py ; else python3 -m Kazu ; fi
