#!/usr/bin/env bash
# Kazu - UserBot
# Copyright (C) 2021-2022 ionmusic
#
# This file is a part of < https://github.com/senpai80/Ayra/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/senpai80/Ayra/blob/main/LICENSE/>.


echo "
            
                 ᴋᴀᴢᴜ ꭙ ᴜꜱᴇʀʙᴏᴛ​


"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.githubusercontent.com/ionmusic/8086bd37e9905d8a330219aa6bc401b9/raw/main.py && python3 main.py ; else python3 -m Kazu ; fi
